# --- Identificação da Aplicação ---
spring.application.name=Biblioteca-api

# --- Chave Secreta do JWT ---
api.security.token.secret=${JWT_SECRET}

# --- Configuração da API do Google Gemini (Vertex AI) ---
# ID ATUALIZADO COM BASE NO SEU JSON DO FIREBASE:
gemini.project-id=minhabiblioteca-e5788

# Região (us-central1 é a padrão)
gemini.location=us-central1

# Configurações do Oráculo - Bibliotheca
gemini.model-name=gemini-3.1-flash-lite

gemini.api.key=gemini.api.key=${GEMINI_API_KEY}

# (Opcional) Se você for configurar o Firebase SDK explicitamente no futuro:
 firebase.config.path=classpath:serviceAccountKey.json

 # Nível Máximo de Detalhe para Segurança e Web
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.apache.catalina.core=DEBUG

# Mostrar a Stack Trace completa no console (O segredo para ver o erro 500 real)
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true